function [] = writeGains(gains,filename)

fileID = fopen(filename,'w');

% Write Gain Header
header = '%%Pr_phi, Ir_phi, Dr_phi, Pr_theta, Ir_theta, Dr_theta, Pr_psi, Ir_psi, Dr_psi, Pa_phi, Pa_theta, Pa_psi, Pvx, Ivx, Dvx, Pvy, Ivy, Dvy, Px, Ix, Dx, Py, Iy, Dy\n';
fprintf(fileID,header);

% Write Gains
fprintf(fileID,[num2str(gains.Pr_phi) ' ,' num2str(gains.Ir_phi) ' ,' num2str(gains.Dr_phi) ' ,' ...
                num2str(gains.Pr_theta) ' ,' num2str(gains.Ir_theta) ' ,' num2str(gains.Dr_theta) ' ,' ...
                num2str(gains.Pr_psi) ' ,' num2str(gains.Ir_psi) ' ,' num2str(gains.Dr_psi) ' ,' ...
                num2str(gains.Pa_phi) ' ,' ...
                num2str(gains.Pa_theta) ' ,' ...
                num2str(gains.Pa_psi) ' ,' ...
                num2str(gains.Pvx) ' ,' num2str(gains.Ivx) ' ,' num2str(gains.Dvx) ' ,' ...
                num2str(gains.Pvy) ' ,' num2str(gains.Ivy) ' ,' num2str(gains.Dvy) ' ,' ...
                num2str(gains.Px) ' ,' num2str(gains.Ix) ' ,' num2str(gains.Dx) ' ,' ...
                num2str(gains.Py) ' ,' num2str(gains.Iy) ' ,' num2str(gains.Dy)]);
fclose(fileID);
            
end